<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>História do Brasil — Era Vargas</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
  <style>
    :root{--wine:#8b1e2d;--wine-dark:#5e1220;--gold:#f1cc54;--cream:#f5efe6;--ink:#1a1a1a;--muted:#666;--line:#d9d9d9}
    *{box-sizing:border-box} html,body{margin:0;min-height:100%;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff}
    .topbar{height:52px;background:var(--wine);color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 16px;position:fixed;inset:0 0 auto;z-index:10;box-shadow:0 1px 5px #0004}
    .brand{display:flex;align-items:center;gap:13px;font-size:13px;font-weight:700}.brand-mark{width:30px;height:30px;border:1px solid #fff8;border-radius:5px;display:grid;place-items:center}.top-actions{display:flex;gap:14px}.top-actions button{border:0;background:none;color:#fff;font-size:17px;cursor:pointer}
    .layout{display:flex;min-height:100vh;padding-top:52px}.sidebar{width:280px;flex:0 0 280px;border-right:1px solid #ddd;padding:13px 8px;background:#fff}.back{display:flex;align-items:center;gap:13px;padding:8px 8px 14px;border-bottom:1px solid #999;font-size:12px;font-weight:700;cursor:pointer}.back i{font-size:19px}.side-heading{display:flex;justify-content:space-between;align-items:center;color:var(--wine);font-size:12px;font-weight:700;padding:13px 5px 8px}.side-tools{display:flex;gap:14px;color:#777;font-size:15px}.search{width:100%;height:34px;border:1px solid #ddd;border-radius:4px;padding:0 10px;font-size:11px;margin-bottom:8px}.lesson-list{list-style:none;padding:0;margin:0}.lesson{display:flex;align-items:center;gap:9px;min-height:40px;padding:5px 7px;border-radius:5px;font-size:11px;cursor:pointer;transition:.15s}.lesson:hover,.lesson.active{background:#f3ede5}.lesson-number{width:23px;height:23px;display:grid;place-items:center;flex:0 0 23px;border-radius:50%;background:var(--wine);color:#fff;font-weight:700}.lesson.exercise .lesson-number{background:transparent;color:#333;font-size:15px}.lesson-name{flex:1;line-height:1.3}.lesson-check{width:10px;height:10px;border:1px solid #ccc;border-radius:50%;flex:0 0 10px}.content{flex:1;min-width:0;padding:48px 6vw 70px;background:#fff}.crumb-row{display:flex;align-items:center;gap:16px;margin-bottom:25px}.breadcrumb{margin:0;font-size:11px;font-weight:600}.breadcrumb-item{color:#b1954a}.breadcrumb-item+.breadcrumb-item::before{content:'›';font-size:18px;color:#555}.next{margin-left:auto;border:0;border-radius:5px;padding:9px 14px;background:var(--gold);font-size:11px;font-weight:700;cursor:pointer}.next:hover{filter:brightness(.96)}h1{font-size:20px;margin:0 0 21px;font-weight:750}h2{font-size:18px;margin:0 0 22px;font-weight:750}.lead,p{font-size:14px;line-height:1.65;text-align:justify;max-width:100%}.section{border-top:1px solid #888;margin:66px 0 43px;padding-top:0}.section h2{margin-top:-1px;padding-top:0}.materials{margin-top:62px}.materials-title{display:inline-block;font:700 18px Georgia,serif;border-bottom:3px solid #333;padding-bottom:3px;margin-bottom:24px}.material{display:flex;align-items:center;gap:16px;padding:14px 18px;border-top:1px solid #555;border-bottom:1px solid #555}.material-icon{font-size:30px}.material-info{flex:1}.material-name{font:700 15px Georgia,serif;margin-bottom:4px}.material-size{font-size:12px;color:var(--muted)}.download{display:flex;align-items:center;gap:28px;font:700 15px Georgia,serif}.download button{border:0;background:none;font-size:23px;cursor:pointer}.empty-card{border:1px solid #ddd;border-radius:8px;background:#fcfaf7;padding:28px;margin-top:35px}.exercise-card{border-left:4px solid var(--wine);background:var(--cream);padding:20px 22px;margin:25px 0;font-size:14px;line-height:1.6}.footer-note{margin-top:45px;color:#777;font-size:12px}
    @media(max-width:800px){.sidebar{width:230px;flex-basis:230px}.content{padding:35px 25px 60px}.crumb-row{align-items:flex-start}.next{white-space:nowrap}.lesson{font-size:11px}}
    .content h1{font-size:16px !important;line-height:1.3;font-weight:700 !important;margin-bottom:16px}.content h2{font-size:15px !important;line-height:1.35;font-weight:700 !important}
    @media(max-width:620px){.sidebar{display:none}.content{padding:30px 20px 50px}.topbar .brand span{display:none}.crumb-row{display:block}.next{margin-top:15px}.lead,p{font-size:15px}.material{padding:14px 8px}.download span{display:none}}
    /* Refinamento visual: interface mais leve, alinhada e profissional */
    :root{--wine:#8f2435;--wine-dark:#681827;--gold:#e8bf4d;--gold-soft:#fff8e5;--cream:#faf7f2;--ink:#26313b;--muted:#71808d;--line:#e8e5e1;--shadow:0 10px 28px rgba(42,31,23,.07)}
    html{scroll-behavior:smooth}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Arial,sans-serif;color:var(--ink);background:#f8f9fb;font-size:13px;letter-spacing:.005em}
    .layout{gap:0;min-height:calc(100vh - 52px);background:#f8f9fb}
    .sidebar{width:270px;flex-basis:270px;padding:18px 13px 24px;background:rgba(255,255,255,.94);border-right:1px solid #e9e7e4;box-shadow:4px 0 20px rgba(39,29,22,.025)}
    .back{height:39px;padding:0 8px 13px;gap:10px;border-bottom:1px solid #ece9e5;color:#47515b;font-size:11px;font-weight:600;transition:color .2s}.back:hover{color:var(--wine)}.back i{font-size:17px}
    .side-heading{padding:19px 5px 10px;color:var(--wine);font-size:11px;letter-spacing:.02em;text-transform:uppercase}.side-tools{gap:12px;font-size:13px}.side-tools i{transition:color .2s}.side-tools i:hover{color:var(--wine)}
    .search{height:34px;margin:0 0 12px;border:1px solid #e5e4e1;border-radius:8px;background:#fbfbfa;color:var(--ink);font-size:11px;outline:0;transition:border-color .2s,box-shadow .2s}.search:focus{border-color:#d7b652;box-shadow:0 0 0 3px rgba(232,191,77,.14)}
    .lesson{min-height:39px;margin:3px 0;padding:6px 7px;gap:9px;border:1px solid transparent;border-radius:8px;color:#4b5660;font-size:10px;transition:background .2s,border-color .2s,transform .2s}.lesson:hover{background:#fbf8f3;border-color:#f1e8d9;transform:translateX(2px)}.lesson.active{background:#fff8e9;border-color:#f4e5bb;color:#3b4147;box-shadow:0 4px 12px rgba(155,119,35,.06)}.lesson-number{width:22px;height:22px;flex-basis:22px;font-size:10px;box-shadow:0 2px 5px rgba(143,36,53,.18)}.lesson.exercise .lesson-number{font-size:14px;box-shadow:none}.lesson-check{border-color:#d9d9d6}
    .content{max-width:1250px;margin:0 auto;padding:38px clamp(28px,5vw,72px) 80px;background:#fff;box-shadow:0 0 35px rgba(30,31,32,.025)}
    .crumb-row{min-height:32px;margin-bottom:27px;align-items:center}.breadcrumb{font-size:10px;letter-spacing:.02em}.breadcrumb-item{color:#a07b2b}.breadcrumb-item.active{color:#68737d}.breadcrumb-item+.breadcrumb-item::before{padding:0 9px;color:#b4b5b3;font-size:16px}.next{padding:8px 14px;border-radius:8px;background:var(--gold);color:#332b18;font-size:10px;box-shadow:0 4px 10px rgba(188,145,33,.16);transition:transform .2s,box-shadow .2s}.next:hover{transform:translateY(-1px);box-shadow:0 7px 14px rgba(188,145,33,.22)}
    .content h1{margin:0 0 13px;color:#202a33;font-size:18px !important;line-height:1.3;font-weight:700 !important;letter-spacing:-.015em}.lead,.content p{max-width:920px;color:#53606b;font-size:13px;line-height:1.75;text-align:left}.section{margin:45px 0 0;padding:26px 0 0;border-top:1px solid #e8e6e2}.content h2{margin:0 0 13px;color:#303b45;font-size:15px !important;line-height:1.4;font-weight:700 !important;letter-spacing:-.005em}.section p{color:#59656f}
    .materials{margin-top:48px;padding-top:4px}.materials-title{margin-bottom:17px;padding-bottom:5px;color:#35414a;font-size:16px;border-bottom:2px solid var(--gold)}.material{min-height:72px;gap:14px;padding:13px 16px;border:1px solid #ebe7e0;border-radius:10px;background:#fff;box-shadow:var(--shadow);transition:transform .2s,box-shadow .2s}.material:hover{background:#fffdfa;transform:translateY(-2px);box-shadow:0 13px 30px rgba(42,31,23,.1)}.material-icon{color:var(--wine);font-size:27px}.material-name{color:#35414a;font-size:14px}.material-size{color:#89939b;font-size:11px}.download{gap:18px;color:#56616b;font-size:13px}.download button{width:32px;height:32px;border-radius:50%;color:var(--wine);font-size:19px;transition:background .2s,transform .2s}.download button:hover{background:#fff4dc;transform:translateY(1px)}
    .exercise-card{margin-top:35px;padding:17px 19px;border:1px solid #f1e3be;border-left:3px solid var(--gold);border-radius:9px;background:var(--gold-soft);color:#5d5542;font-size:13px;line-height:1.7}.footer-note{margin-top:39px;padding-top:16px;border-top:1px solid #eeeae5;color:#a0a7ad;font-size:10px}
    @media(max-width:800px){.sidebar{width:235px;flex-basis:235px}.content{padding:32px 28px 60px}.content h1{font-size:17px !important}.content h2{font-size:14px !important}.lead,.content p{font-size:12px}}
  </style>
</head>
<body>
  <?php
    include("../alexandria-frontend/includes/header.html");
  ?>
  <main class="layout">
    <aside class="sidebar">
      <div class="back" onclick="goBack()"><i class="bi bi-arrow-left"></i><span>Voltar para as videoaulas</span></div>
      <input class="search" id="search" type="search" placeholder="Buscar conteúdo" aria-label="Buscar conteúdo" />
      <ul class="lesson-list" id="lessonList"></ul>
    </aside>
    <section class="content" id="content"></section>
  </main>
  <script>
    const topics = [
      {id:'revolucao-1930', type:'lesson', name:'Era Vargas: Revolução de 1930', short:'1. Revolução de 1930', intro:'Entenda como ocorreu o golpe de Estado cívico-militar que depôs o presidente da República Washington Luís em 24 de outubro de 1930 e impediu a posse do presidente eleito Júlio Prestes, encerrando o período conhecido como República Velha.', sections:[['1. Introdução','A Revolução de 1930 representa um ponto de inflexão fundamental na história política brasileira, marcando o colapso da República Oligárquica e o início de um novo ciclo político sob a liderança de Getúlio Vargas. Este movimento cívico-militar reconfigurou profundamente as estruturas de poder político e econômico do país, abrindo caminho para a Era Vargas e as transformações que caracterizariam o Brasil do século XX.'],['2. Contexto Histórico: A Primeira República e Suas Contradições','A Primeira República brasileira, estabelecida em 1889 após a proclamação da República, foi construída sobre um sistema político que concentrou o poder nas mãos das oligarquias estaduais, particularmente as de São Paulo e Minas Gerais. O período ficou conhecido como República Oligárquica e caracterizou-se pela exclusão política de amplos setores da população e pela manipulação sistemática dos processos eleitorais.'],['3. As Causas Estruturais da Crise de 1930','A crescente insatisfação de outras oligarquias estaduais com o sistema de poder vigente fortaleceu a oposição ao governo federal. Rio Grande do Sul, Paraíba, Bahia e Rio de Janeiro questionavam a concentração das decisões nos interesses paulistas e mineiros. Essa articulação, somada à crise econômica e às disputas eleitorais, forneceu a base para a Revolução de 1930.']]},
      {id:'governo-provisorio',type:'lesson',name:'Era Vargas: Governo Provisório',short:'2. Governo Provisório',intro:'Conheça o período de 1930 a 1934, quando Getúlio Vargas reorganizou o Estado brasileiro e conduziu as primeiras transformações da Era Vargas.',sections:[['1. A centralização do poder','Após a Revolução de 1930, Vargas assumiu o Governo Provisório e dissolveu o Congresso Nacional. A nomeação de interventores para os estados ampliou o controle do governo federal e rompeu com a autonomia das antigas oligarquias.'],['2. Reformas e novas instituições','O período foi marcado pela criação de ministérios e pela organização de políticas trabalhistas, incluindo o Ministério do Trabalho, Indústria e Comércio. Essas medidas aproximaram o Estado dos trabalhadores urbanos e ampliaram a intervenção federal na economia.'],['3. A Revolução Constitucionalista','A pressão por uma nova Constituição culminou na Revolução Constitucionalista de 1932, em São Paulo. O movimento foi derrotado militarmente, mas acelerou a convocação da Assembleia Constituinte.']]},
      {id:'governo-constitucional',type:'lesson',name:'Era Vargas: Governo Constitucional',short:'3. Governo Constitucional',intro:'Analise o período constitucional de 1934 a 1937, marcado por conflitos ideológicos, instabilidade política e crescente autoritarismo.',sections:[['1. A Constituição de 1934','A nova Constituição incorporou direitos sociais, voto secreto e avanços na legislação eleitoral. Vargas foi eleito indiretamente pela Assembleia Constituinte para um mandato constitucional.'],['2. Polarização política','A Ação Integralista Brasileira e a Aliança Nacional Libertadora representaram projetos políticos opostos. A radicalização ideológica e as revoltas de 1935 serviram de justificativa para o endurecimento do governo.'],['3. O caminho para o Estado Novo','O Plano Cohen e o temor de uma revolução comunista foram utilizados para criar um clima de emergência. Em 1937, Vargas fechou o Congresso e iniciou uma nova fase de governo.']]},
      {id:'estado-novo',type:'lesson',name:'Era Vargas: Estado Novo',short:'4. Estado Novo',intro:'Compreenda a ditadura implantada em 1937, sua estrutura autoritária, a propaganda oficial e as políticas de industrialização.',sections:[['1. A ditadura de 1937','O Estado Novo suspendeu as garantias constitucionais, dissolveu os partidos políticos e concentrou poderes no Executivo. A censura e a repressão foram organizadas pelo Departamento de Imprensa e Propaganda.'],['2. Trabalho e industrialização','O governo consolidou direitos trabalhistas e criou mecanismos de controle sindical. Ao mesmo tempo, promoveu a industrialização e fortaleceu empresas estatais estratégicas, como a Companhia Siderúrgica Nacional.'],['3. A política externa e a guerra','Durante a Segunda Guerra Mundial, o Brasil alinhou-se aos Aliados. A participação da Força Expedicionária Brasileira contribuiu para enfraquecer a legitimidade do regime autoritário no pós-guerra.']]},
      {id:'fim-era-vargas',type:'lesson',name:'Era Vargas: Fim da Era Vargas',short:'5. Fim da Era Vargas',intro:'Estude as razões que levaram à deposição de Getúlio Vargas em 1945 e o legado político deixado pela Era Vargas.',sections:[['1. A contradição democrática','A participação do Brasil na luta contra regimes fascistas expôs a contradição entre a defesa da democracia no exterior e a ditadura mantida internamente. A pressão pela redemocratização cresceu entre militares, partidos e setores da sociedade.'],['2. A deposição de 1945','Após conflitos com setores das Forças Armadas, Vargas foi deposto em outubro de 1945. O fim do Estado Novo abriu caminho para eleições e para a Constituição de 1946.'],['3. O legado','A Era Vargas deixou marcas duradouras na legislação trabalhista, na industrialização, na centralização administrativa e na cultura política brasileira.']]},
      {id:'exercicios-1',type:'exercise',name:'Lista de Exercícios 1',short:'Lista de Exercícios 1',intro:'Reforce os conhecimentos sobre a Revolução de 1930 e o contexto da Primeira República.',sections:[['Questão 1','Explique dois fatores políticos que contribuíram para a crise da República Oligárquica e relacione-os à Revolução de 1930.'],['Questão 2','Compare a Política dos Governadores com o projeto político defendido pelos grupos que apoiaram Getúlio Vargas.']]},
      {id:'exercicios-2',type:'exercise',name:'Lista de Exercícios 2',short:'Lista de Exercícios 2',intro:'Pratique os conteúdos sobre o Governo Provisório e o Governo Constitucional.',sections:[['Questão 1','Quais foram as principais medidas de centralização adotadas por Vargas após 1930?'],['Questão 2','Analise a importância da Constituição de 1934 para a história política brasileira.']]},
      {id:'exercicios-3',type:'exercise',name:'Lista de Exercícios 3',short:'Lista de Exercícios 3',intro:'Avalie sua compreensão sobre o Estado Novo e o fim da Era Vargas.',sections:[['Questão 1','Identifique características autoritárias do Estado Novo e explique como a propaganda ajudou a sustentar o regime.'],['Questão 2','Por que a participação brasileira na Segunda Guerra Mundial contribuiu para a crise do Estado Novo?']]}
    ];
    let current = 0;
    const list = document.getElementById('lessonList'), content = document.getElementById('content'), search = document.getElementById('search');
    function renderList(filter='') { list.innerHTML=''; topics.forEach((t,i)=>{if(filter && !t.name.toLowerCase().includes(filter.toLowerCase())) return; const li=document.createElement('li'); li.className=`lesson ${t.type} ${i===current?'active':''}`; li.onclick=()=>t.type==='exercise'?window.location.href='teladequest.php?lista='+encodeURIComponent(t.id.replace('exercicios-','')):openTopic(i); li.innerHTML=`<span class="lesson-number">${t.type==='exercise'?'<i class="bi bi-clipboard"></i>':i+1}</span><span class="lesson-name">${t.name}</span><span class="lesson-check"></span>`; list.appendChild(li);}); }
    function openTopic(index){ current=Math.max(0,Math.min(topics.length-1,index)); const t=topics[current]; history.replaceState(null,'','#'+t.id); renderList(search.value); content.innerHTML=`<div class="crumb-row"><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">História do Brasil</li><li class="breadcrumb-item">Era Vargas</li><li class="breadcrumb-item active">${t.short}</li></ol></nav><button class="next" onclick="openTopic(${Math.min(current+1,topics.length-1)})">${current===topics.length-1?'Concluído':'Próximo'} <i class="bi bi-chevron-right"></i></button></div><h1>${t.short}</h1><p class="lead">${t.intro}</p>${t.sections.map((s,i)=>`<div class="section"><h2>${s[0]}</h2><p>${s[1]}</p></div>`).join('')}${t.type==='exercise'?`<div class="exercise-card"><strong>Instruções:</strong> responda às questões no seu caderno ou no arquivo de atividades. Revise os textos da aula antes de enviar suas respostas.</div>`:`<div class="materials"><div class="materials-title">Materiais</div><div class="material"><div class="material-icon"><i class="bi bi-file-earmark-word"></i></div><div class="material-info"><div class="material-name">Material complementar — ${t.short}</div><div class="material-size">Word - 15.62 KB</div></div><div class="download"><span>Download</span><button title="Baixar material"><i class="bi bi-download"></i></button></div></div></div>`}<div class="footer-note">Tela ${current+1} de ${topics.length} · ${t.name}</div>`; window.scrollTo({top:0,behavior:'smooth'}); }
    function goBack(){history.back();}
    search.addEventListener('input',e=>renderList(e.target.value));
    const hash=location.hash.slice(1), initial=topics.findIndex(t=>t.id===hash); renderList(); if(initial>=0 && topics[initial].type==='exercise'){window.location.href='teladequest.php?lista='+encodeURIComponent(topics[initial].id.replace('exercicios-',''));}else{openTopic(initial>=0?initial:0);}
  </script>
</body>
</html>
