<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>História do Brasil — Era Vargas</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
  <link rel="stylesheet" href="estilo/aula.css">
  
</head>

<body>
  <?php
    include("../alexandria-frontend/includes/header.html");
  ?>
  <main class="layout">
    <aside class="sidebar">
      <div class="back" onclick="goBack()"><i class="bi bi-arrow-left"></i><span>Voltar para as videoaulas</span></div>
      <input class="search" id="search" type="search" placeholder="Buscar conteúdo" aria-label="Buscar conteúdo" />
      <ul class="lesson-list" id="lessonList"></ul>
    </aside>
    <section class="content" id="content"></section>
  </main>
  <script>
    const topics = [
      {id:'revolucao-1930', type:'lesson', name:'Era Vargas: Revolução de 1930', short:'1. Revolução de 1930', intro:'Entenda como ocorreu o golpe de Estado cívico-militar que depôs o presidente da República Washington Luís em 24 de outubro de 1930 e impediu a posse do presidente eleito Júlio Prestes, encerrando o período conhecido como República Velha.', sections:[['1. Introdução','A Revolução de 1930 representa um ponto de inflexão fundamental na história política brasileira, marcando o colapso da República Oligárquica e o início de um novo ciclo político sob a liderança de Getúlio Vargas. Este movimento cívico-militar reconfigurou profundamente as estruturas de poder político e econômico do país, abrindo caminho para a Era Vargas e as transformações que caracterizariam o Brasil do século XX.'],['2. Contexto Histórico: A Primeira República e Suas Contradições','A Primeira República brasileira, estabelecida em 1889 após a proclamação da República, foi construída sobre um sistema político que concentrou o poder nas mãos das oligarquias estaduais, particularmente as de São Paulo e Minas Gerais. O período ficou conhecido como República Oligárquica e caracterizou-se pela exclusão política de amplos setores da população e pela manipulação sistemática dos processos eleitorais.'],['3. As Causas Estruturais da Crise de 1930','A crescente insatisfação de outras oligarquias estaduais com o sistema de poder vigente fortaleceu a oposição ao governo federal. Rio Grande do Sul, Paraíba, Bahia e Rio de Janeiro questionavam a concentração das decisões nos interesses paulistas e mineiros. Essa articulação, somada à crise econômica e às disputas eleitorais, forneceu a base para a Revolução de 1930.']]},
      {id:'governo-provisorio',type:'lesson',name:'Era Vargas: Governo Provisório',short:'2. Governo Provisório',intro:'Conheça o período de 1930 a 1934, quando Getúlio Vargas reorganizou o Estado brasileiro e conduziu as primeiras transformações da Era Vargas.',sections:[['1. A centralização do poder','Após a Revolução de 1930, Vargas assumiu o Governo Provisório e dissolveu o Congresso Nacional. A nomeação de interventores para os estados ampliou o controle do governo federal e rompeu com a autonomia das antigas oligarquias.'],['2. Reformas e novas instituições','O período foi marcado pela criação de ministérios e pela organização de políticas trabalhistas, incluindo o Ministério do Trabalho, Indústria e Comércio. Essas medidas aproximaram o Estado dos trabalhadores urbanos e ampliaram a intervenção federal na economia.'],['3. A Revolução Constitucionalista','A pressão por uma nova Constituição culminou na Revolução Constitucionalista de 1932, em São Paulo. O movimento foi derrotado militarmente, mas acelerou a convocação da Assembleia Constituinte.']]},
      {id:'governo-constitucional',type:'lesson',name:'Era Vargas: Governo Constitucional',short:'3. Governo Constitucional',intro:'Analise o período constitucional de 1934 a 1937, marcado por conflitos ideológicos, instabilidade política e crescente autoritarismo.',sections:[['1. A Constituição de 1934','A nova Constituição incorporou direitos sociais, voto secreto e avanços na legislação eleitoral. Vargas foi eleito indiretamente pela Assembleia Constituinte para um mandato constitucional.'],['2. Polarização política','A Ação Integralista Brasileira e a Aliança Nacional Libertadora representaram projetos políticos opostos. A radicalização ideológica e as revoltas de 1935 serviram de justificativa para o endurecimento do governo.'],['3. O caminho para o Estado Novo','O Plano Cohen e o temor de uma revolução comunista foram utilizados para criar um clima de emergência. Em 1937, Vargas fechou o Congresso e iniciou uma nova fase de governo.']]},
      {id:'estado-novo',type:'lesson',name:'Era Vargas: Estado Novo',short:'4. Estado Novo',intro:'Compreenda a ditadura implantada em 1937, sua estrutura autoritária, a propaganda oficial e as políticas de industrialização.',sections:[['1. A ditadura de 1937','O Estado Novo suspendeu as garantias constitucionais, dissolveu os partidos políticos e concentrou poderes no Executivo. A censura e a repressão foram organizadas pelo Departamento de Imprensa e Propaganda.'],['2. Trabalho e industrialização','O governo consolidou direitos trabalhistas e criou mecanismos de controle sindical. Ao mesmo tempo, promoveu a industrialização e fortaleceu empresas estatais estratégicas, como a Companhia Siderúrgica Nacional.'],['3. A política externa e a guerra','Durante a Segunda Guerra Mundial, o Brasil alinhou-se aos Aliados. A participação da Força Expedicionária Brasileira contribuiu para enfraquecer a legitimidade do regime autoritário no pós-guerra.']]},
      {id:'fim-era-vargas',type:'lesson',name:'Era Vargas: Fim da Era Vargas',short:'5. Fim da Era Vargas',intro:'Estude as razões que levaram à deposição de Getúlio Vargas em 1945 e o legado político deixado pela Era Vargas.',sections:[['1. A contradição democrática','A participação do Brasil na luta contra regimes fascistas expôs a contradição entre a defesa da democracia no exterior e a ditadura mantida internamente. A pressão pela redemocratização cresceu entre militares, partidos e setores da sociedade.'],['2. A deposição de 1945','Após conflitos com setores das Forças Armadas, Vargas foi deposto em outubro de 1945. O fim do Estado Novo abriu caminho para eleições e para a Constituição de 1946.'],['3. O legado','A Era Vargas deixou marcas duradouras na legislação trabalhista, na industrialização, na centralização administrativa e na cultura política brasileira.']]},
      {id:'exercicios-1',type:'exercise',name:'Lista de Exercícios 1',short:'Lista de Exercícios 1',intro:'Reforce os conhecimentos sobre a Revolução de 1930 e o contexto da Primeira República.',sections:[['Questão 1','Explique dois fatores políticos que contribuíram para a crise da República Oligárquica e relacione-os à Revolução de 1930.'],['Questão 2','Compare a Política dos Governadores com o projeto político defendido pelos grupos que apoiaram Getúlio Vargas.']]},
      {id:'exercicios-2',type:'exercise',name:'Lista de Exercícios 2',short:'Lista de Exercícios 2',intro:'Pratique os conteúdos sobre o Governo Provisório e o Governo Constitucional.',sections:[['Questão 1','Quais foram as principais medidas de centralização adotadas por Vargas após 1930?'],['Questão 2','Analise a importância da Constituição de 1934 para a história política brasileira.']]},
      {id:'exercicios-3',type:'exercise',name:'Lista de Exercícios 3',short:'Lista de Exercícios 3',intro:'Avalie sua compreensão sobre o Estado Novo e o fim da Era Vargas.',sections:[['Questão 1','Identifique características autoritárias do Estado Novo e explique como a propaganda ajudou a sustentar o regime.'],['Questão 2','Por que a participação brasileira na Segunda Guerra Mundial contribuiu para a crise do Estado Novo?']]}
    ];
    let current = 0;
    const list = document.getElementById('lessonList'), content = document.getElementById('content'), search = document.getElementById('search');
    function renderList(filter='') { list.innerHTML=''; topics.forEach((t,i)=>{if(filter && !t.name.toLowerCase().includes(filter.toLowerCase())) return; const li=document.createElement('li'); li.className=`lesson ${t.type} ${i===current?'active':''}`; li.onclick=()=>t.type==='exercise'?window.location.href='teladequest.php?lista='+encodeURIComponent(t.id.replace('exercicios-','')):openTopic(i); li.innerHTML=`<span class="lesson-number">${t.type==='exercise'?'<i class="bi bi-clipboard"></i>':i+1}</span><span class="lesson-name">${t.name}</span><span class="lesson-check"></span>`; list.appendChild(li);}); }
    function openTopic(index){ current=Math.max(0,Math.min(topics.length-1,index)); const t=topics[current]; history.replaceState(null,'','#'+t.id); renderList(search.value); content.innerHTML=`<div class="crumb-row"><nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">História do Brasil</li><li class="breadcrumb-item">Era Vargas</li><li class="breadcrumb-item active">${t.short}</li></ol></nav><button class="next" onclick="openTopic(${Math.min(current+1,topics.length-1)})">${current===topics.length-1?'Concluído':'Próximo'} <i class="bi bi-chevron-right"></i></button></div><h1>${t.short}</h1><p class="lead">${t.intro}</p>${t.sections.map((s,i)=>`<div class="section"><h2>${s[0]}</h2><p>${s[1]}</p></div>`).join('')}${t.type==='exercise'?`<div class="exercise-card"><strong>Instruções:</strong> responda às questões no seu caderno ou no arquivo de atividades. Revise os textos da aula antes de enviar suas respostas.</div>`:`<div class="materials"><div class="materials-title">Materiais</div><div class="material"><div class="material-icon"><i class="bi bi-file-earmark-word"></i></div><div class="material-info"><div class="material-name">Material complementar — ${t.short}</div><div class="material-size">Word - 15.62 KB</div></div><div class="download"><span>Download</span><button title="Baixar material"><i class="bi bi-download"></i></button></div></div></div>`}<div class="footer-note">Tela ${current+1} de ${topics.length} · ${t.name}</div>`; window.scrollTo({top:0,behavior:'smooth'}); }
    function goBack(){history.back();}
    search.addEventListener('input',e=>renderList(e.target.value));
    const hash=location.hash.slice(1), initial=topics.findIndex(t=>t.id===hash); renderList(); if(initial>=0 && topics[initial].type==='exercise'){window.location.href='teladequest.php?lista='+encodeURIComponent(topics[initial].id.replace('exercicios-',''));}else{openTopic(initial>=0?initial:0);}
  </script>
</body>
</html>
